### ISSUE TITLE
Maximize Button Hidden in Top Ba 

### ISSUE THREAD

**Issue by blanketish** [naveensagar765/SnowFox#5]
The green button that is supposed to maximize the window is not showing up in the top bar. Instead, only the red and yellow buttons show. 

Could you please fix this issue? I tried reinstalling the theme but this did not work. Thank you.

**Comment by naveensagar765** [comment]
can you share screenshots?

**Comment by naveensagar765** [comment]
> The green button that is supposed to maximize the window is not showing up in the top bar. Instead, only the red and yellow buttons show.
> 
> Could you please fix this issue? I tried reinstalling the theme but this did not work. Thank you.

### can you share screenshots?

**Comment by blanketish** [comment]
https://imgur.com/j1fFhYT

**Comment by naveensagar765** [comment]
I have made some changes. Could you please re-download the theme and test it?
If this doesn't work, please let me know. If it works, please close the issue. Thank you

**Comment by blanketish** [comment]
Hello. I tried reloading the chrome folder but it still is not working. 

It could be because I am using the Linux distribution Pop OS!_ which is a fork of Ubuntu. I really appreciate your help and time to this theme. It is an amazing theme!

**Comment by naveensagar765** [comment]
did you downloaded it again
